"use client";

import { useMarketplaceClient } from "@/components/providers/marketplace";
import { useCallback, useRef, useState } from "react";

// ── Types ──────────────────────────────────────────────────────────────────

export interface SitecoreTreeNode {
  itemId: string;
  name: string;
  path: string;
  hasChildren: boolean;
  template?: { name: string };
  /** ISO string from the __Updated standard field */
  updated?: string;
  /** Username from the __Updated by standard field */
  updatedBy?: string;
  /** GUID from the __Revision standard field — regenerated by Sitecore on every save */
  revision?: string;
}

interface RawChildNode {
  itemId: string;
  name: string;
  path: string;
  hasChildren: boolean;
  template?: { name: string };
  updated?: { value: string } | null;
  updatedBy?: { value: string } | null;
  revision?: { value: string } | null;
}

interface GraphQLItemResponse {
  item?: {
    itemId: string;
    name: string;
    path: string;
    children?: {
      nodes: RawChildNode[];
    };
  };
}

// ── GraphQL query ──────────────────────────────────────────────────────────

const GET_SITECORE_ITEMS = /* GraphQL */ `
  query GetSitecoreItems($path: String!, $systemLocale: String!) {
    item(
      where: {
        database: "master"
        path: $path
        language: $systemLocale
      }
    ) {
      itemId
      name
      path
      children {
        nodes {
          itemId
          name
          hasChildren
          path
          template {
            name
          }
          updated: field(name: "__Updated") {
            value
          }
          updatedBy: field(name: "__Updated by") {
            value
          }
          revision: field(name: "__Revision") {
            value
          }
        }
      }
    }
  }
`;

// ── Hook ───────────────────────────────────────────────────────────────────

export function useSitecoreTree(sourceContextId: string | null) {
  const client = useMarketplaceClient();

  // Map<path, SitecoreTreeNode[]> — loaded children per parent path
  const [childrenMap, setChildrenMap] = useState<Map<string, SitecoreTreeNode[]>>(
    new Map()
  );
  // Set of paths currently being fetched
  const [loadingPaths, setLoadingPaths] = useState<Set<string>>(new Set());
  // Map<path, error message>
  const [errorMap, setErrorMap] = useState<Map<string, string>>(new Map());

  // Ref to avoid stale closure issues when multiple expansions happen quickly
  const childrenMapRef = useRef(childrenMap);
  childrenMapRef.current = childrenMap;

  const fetchChildren = useCallback(
    async (path: string) => {
      if (!sourceContextId) return;
      // Already loaded or currently loading
      if (childrenMapRef.current.has(path)) return;

      setLoadingPaths((prev) => new Set(prev).add(path));
      setErrorMap((prev) => {
        const next = new Map(prev);
        next.delete(path);
        return next;
      });

      try {
        const res = await client.mutate("xmc.authoring.graphql", {
          params: {
            body: {
              query: GET_SITECORE_ITEMS,
              variables: { path, systemLocale: "en" },
            },
            query: { sitecoreContextId: sourceContextId },
          },
        });

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const data = (res?.data as any)?.data as GraphQLItemResponse | undefined;
        const rawNodes = data?.item?.children?.nodes ?? [];
        // Flatten the nested `updated` field value into the node object
        const nodes: SitecoreTreeNode[] = rawNodes.map((n) => ({
          itemId: n.itemId,
          name: n.name,
          path: n.path,
          hasChildren: n.hasChildren,
          template: n.template,
          updated: n.updated?.value,
          updatedBy: n.updatedBy?.value,
          revision: n.revision?.value,
        }));

        setChildrenMap((prev) => {
          const next = new Map(prev);
          next.set(path, nodes);
          return next;
        });
      } catch (err) {
        setErrorMap((prev) => {
          const next = new Map(prev);
          next.set(
            path,
            err instanceof Error ? err.message : "Failed to load children"
          );
          return next;
        });
      } finally {
        setLoadingPaths((prev) => {
          const next = new Set(prev);
          next.delete(path);
          return next;
        });
      }
    },
    [client, sourceContextId]
  );

  /** Returns cached children for a path, or undefined if not yet loaded */
  const getChildren = useCallback(
    (path: string): SitecoreTreeNode[] | undefined => {
      return childrenMap.get(path);
    },
    [childrenMap]
  );

  /** Triggers a fetch for a path's children if not already cached */
  const expandNode = useCallback(
    (path: string) => {
      fetchChildren(path);
    },
    [fetchChildren]
  );

  const isLoadingPath = useCallback(
    (path: string) => loadingPaths.has(path),
    [loadingPaths]
  );

  const getError = useCallback(
    (path: string) => errorMap.get(path) ?? null,
    [errorMap]
  );

  return { getChildren, expandNode, isLoadingPath, getError };
}
